SPANDigital/presidium-theme-website

- layouts/_default/baseof.html
> removed scrollspy

- assets/_sass/_structure.scss
Add more margin below the last bullet point in an article to allow it to have even spacing.  Ignore the prettier formatting, the change I made is on line 388
[PRSDM-2100 Bugfix gap](https://spandigital.atlassian.net/browse/PRSDM-2100)
> PRSDM-2100: Add more margin to the bottom of bullet points

- assets/_sass/_syntax.scss
> fix code font size

- layouts/_default/baseof.html
- layouts/partials/analytics.html
> added analytics script and var

- assets/_sass/_structure.scss
- assets/_sass/bootstrap/bootstrap/_variables.scss
- layouts/partials/article.html
Fixed the heading sizes for h3,h4,h5 to be larger than the base font
> fix(PRS-2241): fixed heading sizes

- layouts/partials/nav-item.html
> Add roles to nav item

- assets/_sass/_structure.scss
- assets/_sass/_tooltips.scss
- layouts/_default/baseof.html
- Adjusted the anchor offset to prevent the toolbar from overlapping the title. 
- Right-aligned the tooltip to prevent it from overflowing 
[PRS-2407](https://spandigital.atlassian.net/browse/PRSDM-2407)
[PRSDM-93](https://spandigital.atlassian.net/browse/PRSDM-93)
> fix(anchor): fix anchor offset

- assets/_sass/_structure.scss
Removed the bottom margin on nested lists
[PRSDM-2556](https://spandigital.atlassian.net/browse/PRSDM-2556)
> fix(PRS-2556): remove margin for nested lists

- layouts/partials/article.html
Reduced the heading size for child (nested) articles
[PRS-2558](https://spandigital.atlassian.net/browse/PRSDM-2558)
> fix(PRS-2558): reduce heading size for nested articles

- assets/_sass/_navbar.scss
- assets/_sass/_structure.scss
- layouts/_default/baseof.html
Fixed the menu styles for mobile
[PRSDM-2560](https://spandigital.atlassian.net/browse/PRSDM-2560)
> Mobile styles

- assets/_sass/_structure.scss
> fix(PRS-2560): fixed toolbar overflow

- assets/_sass/_structure.scss
Added a new css class for the article WYSIWYG options.
https://spandigital.atlassian.net/browse/PRSDM-2617
> Added article options class for WYSIWYG buttons

- assets/_sass/_navbar.scss
- layouts/partials/navigation.html
Added a placeholder for a drop down which is used to export PDFs. Also added the accompanying styles.
https://spandigital.atlassian.net/browse/PRSDM-2711
> Added a CSS grid with styles for a react-select component

- layouts/partials/article.html
Added permalink to use for wysiwyg
[JIRA](https://spandigital.atlassian.net/browse/PRSDM-2744)
> inject-permalink-for-wysiwyg

- assets/_sass/_editor.scss
- static/assets/svg/loading-spinner-editor.svg
Added classes for the new editor loading spinner which sits next to "Edit Article" header.
https://spandigital.atlassian.net/browse/PRSDM-2910
> Added editor loading spinner class and icon

- assets/_sass/_editor.scss
Removed the caption editor for the EditorJs quote plugin.
https://spandigital.atlassian.net/browse/PRSDM-2923
> Remove caption editor

- assets/_sass/_structure.scss
Limit the width of text content so that it's easier to read.
https://spandigital.atlassian.net/browse/PRSDM-2885
> Limit paragraph and list text width

- assets/_sass/_structure.scss
This reverts commit ef16f63330bd4dffc757b52d228e3282f3d37fd0.
Reverted the change from https://spandigital.atlassian.net/browse/PRSDM-2885
https://spandigital.atlassian.net/browse/PRSDM-2962
> Revert "Limit paragraph and list text width"

- assets/_sass/_editor.scss
Preload icons so they don't delay when they need to be shown.
https://spandigital.atlassian.net/browse/PRSDM-2949
> Preload icons

- CHANGELOG.md
- layouts/partials/article.html
- pull_request_template.md
Added develop branch and changelog
- Added develop branch
- Added change log
- Update PR template
- Protected main branch
[Jira Link](https://spandigital.atlassian.net/browse/PRSDM-2981)
N/A
N/A
> added dev branch, changelog and update PR template

- CHANGELOG.md
- assets/_sass/_structure.scss
> ensure site content wraps correctly

- CHANGELOG.md
- assets/_sass/_editor.scss
Fixed the modal <p> element font size.
https://spandigital.atlassian.net/browse/PRSDM-3035
> Corrected font size

- CHANGELOG.md
- assets/_sass/_editor.scss
Accompanies https://github.com/SPANDigital/presidium-js-enterprise/pull/237.
> Editor Popup Panel Animation

- assets/_sass/_navbar.scss
- layouts/_default/baseof.html
This PR adds the section path to the article, so we can batch load article meta-data from the API based on section
> Add section path for article batching

- assets/_sass/_structure.scss
- layouts/partials/article/title.html
This PR sets the icon edit icon alignment for https://github.com/SPANDigital/presidium-js-enterprise/pull/315
https://spandigital.atlassian.net/browse/PRSDM-3920
> Set default alignment and remove old styles

- assets/_sass/_structure.scss
Updated the default font size to match the enterprise
https://spandigital.atlassian.net/browse/PRSDM-3876
> Set default font size to match enterprise

- assets/_sass/_editor.scss
- assets/_sass/_navbar.scss
- assets/_sass/_structure.scss
- layouts/partials/page/script.html
General UI fixes
Description
General UI fixes
Issue
[spandigital.atlassian.net/browse/PRSDM-4175](https://spandigital.atlassian.net/browse/PRSDM-4175)
> General UI fixes

- layouts/_default/baseof.html
- layouts/partials/page/script.html
Adjusted the string for the location of the scripts
[PRSDM-4252](https://spandigital.atlassian.net/browse/PRSDM-4252)
> PRSDM-4252 - Presidium UAT site lacks Web Tracking Protections

- layouts/partials/searchmap/item.html
Updates the searchmap to add a summary for each article based on the first paragraph 
https://spandigital.atlassian.net/browse/PRSDM-4560
> Add summary to searchmap

- CHANGELOG.md
- layouts/partials/navigation/menu-title.html
- layouts/partials/navigation/nav-item.html
Fix latest theme breaking the Chronicle
[Issue](https://spandigital.atlassian.net/browse/PRSDM-4681)
> PRSDM-4681: fix latest theme breaking the chronicle

- assets/_sass/bootstrap/bootstrap/_code.scss
Updated code block position so we can add the copy to code block button, [see PR](https://github.com/SPANDigital/presidium-js-enterprise/pull/420)
https://spandigital.atlassian.net/browse/PRSDM-3819
> Update code block position to relative

- CHANGELOG.md
- layouts/partials/navigation/menu-title.html
- layouts/partials/navigation/nav-item.html
Reverted previous change and applied change in Chronicle since previous change affected handbook and docs-internal
[Issue](https://spandigital.atlassian.net/browse/PRSDM-4681)
> Revert previous changes and apply fixes in chronicle

- CHANGELOG.md
- layouts/partials/page/list.html
Add classname to index file content, for editor controls to target it
Add classname to index file content, for editor controls to target it
https://spandigital.atlassian.net/browse/PRSDM-4577
> Add classname to index file content, for editor controls to target it

- assets/_sass/_default-variables.scss
- assets/_sass/_structure.scss
- assets/_sass/bootstrap/bootstrap/_code.scss
- assets/_sass/bootstrap/bootstrap/_glyphicons.scss
- assets/_sass/bootstrap/bootstrap/_normalize.scss
- assets/_sass/bootstrap/bootstrap/_scaffolding.scss
- assets/_sass/bootstrap/bootstrap/_variables.scss
- assets/_sass/bootstrap/bootstrap/mixins/_reset-text.scss
- layouts/_default/baseof.html
Fix general article styling issues
Fix general article styling issues
https://spandigital.atlassian.net/browse/PRSDM-4868
> Fix general article styling issues

- layouts/partials/page/script.html
- Ensure the menu title toggles correctly on click
- Ensure the caret works as expected on both handbook and chonicle
- Ensure the caret displays correctly with the scroll-spy
[PRSDM-4854](https://spandigital.atlassian.net/browse/PRSDM-4854)
https://github.com/SPANDigital/presidium-theme-website/assets/34862470/4288c661-a5e3-406d-8df0-b3d13686ec2f
> PRSDM-4854: SPAN Chronicle Left Nav carrot error

- .github/CODEOWNERS
- CHANGELOG.md
Add codeowner file
Add codeowner file
https://spandigital.atlassian.net/browse/PRSDM-4891
> Add codeowner file

- CHANGELOG.md
- assets/_sass/_editor.scss
GA release of User Dashboard
GA release of User Dashboard
https://spandigital.atlassian.net/browse/PRSDM-4928
N/A
> GA release of User Dashboard

- CHANGELOG.md
- layouts/partials/page/script.html
Fix Left Nav carrot error
This is a cherry pick of this [ticket](https://spandigital.atlassian.net/browse/PRSDM-4854) & [PR](https://github.com/SPANDigital/presidium-theme-website/pull/245) into main to release to apple
https://spandigital.atlassian.net/browse/PRSDM-4908
> Fix Left Nav carrot error

- .github/CODEOWNERS
- theme.toml
Master to Main change
Master to Main change
https://spandigital.atlassian.net/browse/PRSDM-4927
> Master to Main change

- layouts/_default/baseof.html
- layouts/partials/page/script.html
> hotfix: include config script

- CHANGELOG.md
- assets/_sass/_structure.scss
- layouts/shortcodes/iframe.html
Fix iframe closing issue
Fix iframe closing issue
https://spandigital.atlassian.net/browse/PRSDM-5153
https://spandigital.atlassian.net/browse/PRSDM-5147
https://spandigital.atlassian.net/browse/PRSDM-5157
> Fix iframe closing issue

- CHANGELOG.md
- layouts/partials/article/root.html
- layouts/partials/page/header.html
- layouts/partials/page/list.html
- layouts/partials/page/script.html
- layouts/partials/searchmap/item.html
Remove shortcode excluding empty files
Remove shortcode excluding empty files
https://spandigital.atlassian.net/browse/PRSDM-5230
> Remove shortcode excluding empty files

- assets/_sass/_editor.scss
- layouts/_default/baseof.html
- layouts/partials/article/authorisvalid.html
- layouts/partials/article/root.html
- layouts/partials/article/validation.html
- layouts/partials/common/formatmessage.html
Add validation on frontmatter author field
Description
Add validation on frontmatter author field
Issue
[spandigital.atlassian.net/browse/PRSDM-5353](https://spandigital.atlassian.net/browse/PRSDM-5353)
To test this you'll need to add this to the config.yamls in the respective modules
```
params:
...
frontmatter:
- key: author
type: email
required: true
- key: title
type: text
required: true
```
> Add validation on frontmatter author field

- .gitignore
- .husky/pre-commit
- .stylelintrc
- CHANGELOG.md
- assets/_sass/_default-fonts.scss
Fix open sans font import
Fix open sans font import
https://spandigital.atlassian.net/browse/PRSDM-5893
> Fix open sans font import

- CHANGELOG.md
- assets/_sass/_default-fonts.scss
- assets/_sass/_default-variables.scss
Font & typography alignements
Font & typography alignements
https://spandigital.atlassian.net/browse/PRSDM-5980
> Font & typography alignements

- CHANGELOG.md
- assets/_sass/_navbar.scss
- layouts/_default/baseof.html
- layouts/partials/page/script.html
Add resizer back
Add resizer back
https://spandigital.atlassian.net/browse/PRSDM-6012
> Add resizer back

- CHANGELOG.md
- layouts/_default/baseof.html
Splitting of js & css build files
Splitting of js & css build files
https://spandigital.atlassian.net/browse/PRSDM-6018
> feat: Splitting of js & css build files

- CHANGELOG.md
- assets/_sass/_navbar.scss
- layouts/partials/navigation/brand.html
Center navbar header content, fix navbar header image size & improve how navbar determines height
Center navbar header content, fix navbar header image size & improve how navbar determines height
https://spandigital.atlassian.net/browse/PRSDM-6146
> fix: Center navbar header content, fix navbar header image size & improve how navbar determines height

- layouts/_default/baseof.html
- layouts/partials/article/root.html
Updated some templates that handle the `.File.Path` and the `.Path` values for the latest version of Hugo.
https://spandigital.atlassian.net/browse/PRSDM-6151
> fix: PRSDM-6151 ensure our hugo version is up to date

- CHANGELOG.md
- layouts/partials/article/authorisvalid.html
- layouts/partials/article/validation.html
Remove Apple specific content
Remove Apple specific content
https://spandigital.atlassian.net/browse/PRSDM-6228
> Remove Apple specific content

- CHANGELOG.md
- assets/_sass/_navbar.scss
feat: https://spandigital.atlassian.net/browse/PRSDM-6207 - add Quality Category on brand styling
feat: https://spandigital.atlassian.net/browse/PRSDM-6207
> feat: https://spandigital.atlassian.net/browse/PRSDM-6207 - add Quality Category on brand styling

- .gitignore
- CHANGELOG.md
- layouts/partials/article/root.html
- layouts/partials/page/header.html
Adding voice over support for article titles
https://spandigital.atlassian.net/browse/PRSDM-6345
> fix: PRSDM-6345 add aria label to articles

- layouts/partials/article/content.html
- layouts/partials/article/root.html
- layouts/partials/page/header.html
- layouts/partials/page/list.html
Removed arial-label from the div and added to article html element.
Removed arial-label from the div with class="article" and added it to article html element.
https://spandigital.atlassian.net/browse/PRSDM-6345
> feat: PRSDM-6345 aria labels on article html tags for develop branch

- CHANGELOG.md
- layouts/_default/baseof.html
fix: https://spandigital.atlassian.net/browse/PRSDM-6522 - attend to deprecation warnings
- Function Length ([see reference](https://martinfowler.com/bliki/FunctionLength.html))
- Meaningful Names ([see reference](https://learning.oreilly.com/library/view/clean-code-a/9780136083238/chapter02.xhtml))
- DRY ([see reference](https://java-design-patterns.com/principles/#keep-things-dry))
- YAGNI ([see reference](https://java-design-patterns.com/principles/#yagni))
> fix: https://spandigital.atlassian.net/browse/PRSDM-6522 - attend to deprecation warnings

- .releaserc.json
- Remove comments on successful commit
- Function Length ([see reference](https://martinfowler.com/bliki/FunctionLength.html))
- Meaningful Names ([see reference](https://learning.oreilly.com/library/view/clean-code-a/9780136083238/chapter02.xhtml))
- DRY ([see reference](https://java-design-patterns.com/principles/#keep-things-dry))
- YAGNI ([see reference](https://java-design-patterns.com/principles/#yagni))
> ci: remove comments for successful releases
