- assets/_sass/_navbar.scss
Linked to bootswatch removal:  https://github.com/SPANDigital/presidium-theme-website/pull/98/files 
This is an amendment fix to that PR
The border being applied to the navbar in presidium handbook docs is using an id + class selector which gives it a higher specificity. The consequence of this is that it prevents the apple theme from overriding the border in their own sites. This PR fixes that issue 
[PRSDM-2038](https://spandigital.atlassian.net/browse/PRSDM-2038)
> Reduce specificity to allow overriding nav border

- assets/_sass/_navbar.scss
The sidebar navigation panel text was not overflowing as intended, changed it so that the entire word breaks onto the next line instead of a portion of the letters. 
[PRSDM-2102](https://spandigital.atlassian.net/browse/PRSDM-2102)
> fix overflow issue in apple sidebar navigation

- layouts/partials/article.html
- layouts/partials/nav-item.html
Titles that have a dash do not create a slug correctly
When a slug was created for a title with a dash in it it would create a link with triple dashes.
Title example: This is a Title - Dashed
Before fix: this-is-a-title---dashed
After fix: this-is-a-title-dashed
Check the slug/link of a title with a dash
> PRSDM-dashed-link-fix

- layouts/partials/searchmap-item.html
Some of the slugs in the search map were nil, breaking some of the article links in the "Feedback" section.
[PRS-2311
](https://spandigital.atlassian.net/browse/PRSDM-2311)
> Searchmap slug fix

- layouts/_default/single.html
- layouts/shortcodes/tooltip.html
- Changed the tooltip URL to be the same as the article URL i.e `parentpermalink/#slug`.
- Fixed the layout for single-page articles. 
[PRS-2289](https://spandigital.atlassian.net/browse/PRSDM-2289?atlOrigin=eyJpIjoiOWY2NDEwOTg0ZTc4NDMzYWE4M2I5NDI1ODlkODJlYjciLCJwIjoiaiJ9)
- Make sure tooltip links work
- Make sure article references work for example
```
[Click me]({{< ref "/introduction/history.md" >}})
```
or
```
[Click me]({{< ref "/introduction/#history" >}})
```
> Tooltip Fixes

- assets/_sass/_syntax.scss
Removed the font size override for code blocks. See related [PR](https://github.com/SPANDigital/presidium-theme-apple/pull/20)
[PRS-2337](https://spandigital.atlassian.net/browse/PRSDM-2337)
> Code syntax font size

- layouts/partials/nav-item.html
Disabled the menu expander when there are no children. See related [PR](https://github.com/SPANDigital/presidium-theme-apple/pull/22) for the styling fixes
[PRS-2339](https://spandigital.atlassian.net/browse/PRSDM-2339)
> Fixed menu expander

- assets/_sass/_structure.scss
The toolbar is obscuring some of the content. This adds a small `margin-top` to push it back down.
https://spandigital.atlassian.net/browse/PRSDM-2497
> Added margin to push the content back to its original position.

- assets/_sass/_structure.scss
Created a max width limit for the editor.
Stipulating a max width stops the EditorJS elements from being misplaced when adjusting the window size.
https://spandigital.atlassian.net/browse/PRSDM-2620
> Set max width to 650px.

- assets/_sass/_structure.scss
Moved the block tool to the left side of the editor to be more in line with designs.
https://spandigital.atlassian.net/browse/PRSDM-2726
> Moved block tool to the left side of the editor

- CHANGELOG.md
- layouts/partials/article.html
Inject the article path into an HTML attribute for use in the React app.
https://spandigital.atlassian.net/browse/PRSDM-2985
> Inject article path into attribute

- assets/_sass/_image.scss
- assets/_sass/_navbar.scss
- assets/_sass/_structure.scss
PRSDM-2719: Reintroduce z-index variables
Replaces hard-coded z-index values with pre-existing variables.
https://spandigital.atlassian.net/browse/PRSDM-2719
1. Open an article with an image
2. Click on the image
3. Observe the modal button existing above the navbar
> Fix z-index references

- assets/_sass/_navbar.scss
Moves existing z-index setting to `.dropdown`, raising the entire dropdown above the scrollbar.
https://spandigital.atlassian.net/browse/PRSDM-2952
1. Visit site with entries
2. Expand entries until they overflow the area
3. Click on the dropdown arrow
> Move z-index to dropdown parent

- CHANGELOG.md
- assets/_sass/_editor.scss
Align editor-popup-panel text
Align editor-popup-panel text
https://spandigital.atlassian.net/browse/PRSDM-2971
Confirmed the text is now centred
> Align editor-popup-panel text

- CHANGELOG.md
- layouts/_default/list.html
- layouts/shortcodes/img.html
Updated img shortcode to allow spaces
You could not have spaces in the attributes field like styles, it would break and add each space as a new element
[JIRA link](https://spandigital.atlassian.net/browse/PRSDM-2882)
Use an image shortcode `{{< img src="" alt="" caption="" style="">}}` and add multiple styles with spaces after the colon or semi-colon. It should still work as expected
N/A
> PRSDM-2882-inline-img-attr-spacing

- CHANGELOG.md
- assets/_sass/_tooltips.scss
- layouts/shortcodes/tooltip.html
Display all content within a tooltip. Scroll when the content exceeds the bounds.
https://spandigital.atlassian.net/browse/PRSDM-3158
1. Checkout "SPAN-Approach-2.0" on SPAN Handbook.
2. Go to docs/span-handbook/#contribution
3. Hover over a tooltip.
4. Scroll through the content.
* [ x Did you update the CHANGELOG?
> Display entire tooltip content. Enable scrolling.

- CHANGELOG.md
- assets/_sass/_navbar.scss
Position the pdf button correctly when the page width is small.
https://spandigital.atlassian.net/browse/PRSDM-3223
> Added media query for pdf button when the page is narrow

- CHANGELOG.md
- assets/_sass/_structure.scss
Brought styles over from the React app. Placed the article option buttons to the right of the header when the viewport is narrowed. Limit the title width to account for the permalink and article options when the screen is narrow.
https://spandigital.atlassian.net/browse/PRSDM-3224
1. Checkout the branch of https://github.com/SPANDigital/presidium-js-enterprise/pull/262
2. Adjust the width of the page so that is is below 768px.
3. Observe the positioning of the article options.
> Styles for article options when the viewport is narrow

- CHANGELOG.md
- layouts/shortcodes/img.html
Images using the shortcode no longer render in the PDF document
Images in the shortcode need the baseurl to render in the PDF
[PRSDM-3226](https://spandigital.atlassian.net/browse/PRSDM-3226)
Create a PDF from a doc site that has an images using the `img` shortcode
N/A
> Prsdm 3226 fix pdf shortcode img

- CHANGELOG.md
- layouts/partials/article.html
Added permalink attribute to the article div. This is so that we can edit landing pages. i.e. pages that have the same title as the section.
https://spandigital.atlassian.net/browse/PRSDM-3285
> Added permalink attribute to the article div

- CHANGELOG.md
- layouts/_default/baseof.html
PRSDM-3388: added site wide theme for mermaid
John was looking at initialising a site wide theme for mermaid graphs using the Span theme colours. This PR adds the site wide theme to mermaid which will by default theme all graphs across presidium sites using this theme.
https://spandigital.atlassian.net/browse/PRSDM-3388
> added site wide mermaid theme with Span colours

- CHANGELOG.md
- layouts/partials/article.html
- layouts/partials/nav-item.html
- layouts/partials/searchmap-item.html
- layouts/shortcodes/tooltip.html
Replaced multiple dashes in the slugs with a single dash. The multiple dashes broke links in the generated PDF.
[PRSDM-3465](https://spandigital.atlassian.net/browse/PRSDM-3465)
Create a PDF from a doc site that has glossary items with titles containing a space followed by a special character. For example "Apple Media Discovery (AMP)"
N/A
> Prsdm 3465 replace multiple dashes in slugs with one

- CHANGELOG.md
- layouts/shortcodes/img.html
Fixed image shortcode in top-level _index.md
Fixed a bug where image shortcodes in top-level `_index.md` files using the `{{< img src="..." >}}` format threw and error, because `.Page.Parent.Parent` does not exist in that file. Added a condition to check for `.Page.Parent.Parent`
https://spandigital.atlassian.net/browse/PRSDM-3563
Before change, adding an image in the `{{< img src="..." >}}` format (not the `![...]({{% baseurl %}}/images/....png)` format) in a level `_index.md` file would break the site. After the change doing so works.
> Fixed image shortcode in top level _index.md

- CHANGELOG.md
- layouts/partials/json-nav-item.html
Fix the .File.Filename warning
Fix the .File.Filename warning for a zero object by using with
https://spandigital.atlassian.net/browse/PRSDM-3569
Before the fix, run `hugo serve` on your docs of choice and see the error. After the fix do the same, but no warning now
Before:
After:
> Fix .File.Filename warning

- CHANGELOG.md
- assets/_sass/_editor.scss
Fixed a bug where the tune menu and popover would be placed off-screen when the viewport is narrow.
https://spandigital.atlassian.net/browse/PRSDM-3225
> Override EditorJS styles

- CHANGELOG.md
- layouts/partials/searchmap/root.html
The Searchmap has nested values that is breaking the search import. This is only breaking on Chronicle and we cannot find the bug as we suspect it is in hugo.
This fix flattens the returned slice through a simple iteration append.
[](https://spandigital.atlassian.net/browse/PRSDM-3618)
A simple view with this fix. Indentation implies depth/ nesting.
```
"section": "Meetups",
"section": "Meetups",
"section": "Meetups",
"section": "Meetups",
"section": "Case Studies",
"section": "Case Studies",
```
Without fix:
```
"section": "Meetups",
"section": "Meetups",
"section": "Case Studies", // <-- see indentation
"section": "Case Studies",
```
> Flatten searchmap by appending returned searchmap item individually

- assets/_sass/_structure.scss
The `<section>` was recently removed with the refactor but there were still some styles that referenced it. I removed the `section` selection from the styles to fix the icon alignment.
I also logged a follow-up ticket to move the article option styles from the theme to enterprise: https://spandigital.atlassian.net/browse/PRSDM-3707
https://spandigital.atlassian.net/browse/PRSDM-3704
> fix(wysiwyg): remove section from styles

- config.yml
- layouts/_default/baseof.html
- layouts/index.navigation.js
This PR is a tech spike for lazy loading the nav.
Summary;
When `lazyLoad` is enabled, it renders the nav to a `navigation.js` file which is then loaded and injected into the page before rendering. It removes the need to render and upload an entire site when an article is added, deleted, or renamed. 
Live on: https://eng.presidium.spandigital.io/
There is still some room for improvement. Here are a couple of issues I found
- The `navigation.js` file needs to be fetched before the page renders so it increases the page load time. This can be fixed by adjusting the API cache policy.;
- The JS media/mime type is OS-dependent. It needs to be set to `text/javascript` on MacOS but `application/javascript` on Linux. Haven't found a solution yet.
https://spandigital.atlassian.net/browse/PRSDM-3493
> Techspike - Nav Lazyload

- CHANGELOG.md
- assets/_sass/_structure.scss
This PR fixes the alignment of the anchor tag for the Permalink.
https://spandigital.atlassian.net/browse/PRSDM-3818
> fix: align permalink anchor

- CHANGELOG.md
- assets/_sass/_navbar.scss
Fix UI Overlap glitch in Export Project as PDF feature
The dropdown button uses a form dropdown input component package. The styling added in the theme broke the default behaviour to close the dropdown with a click external to the dropdown. Moving the culprit CSS to the child class did the trick.
https://spandigital.atlassian.net/browse/PRSDM-2952
Go into any project. Click the download as PDF button. Observe that it no longer persists and closes when clicking elsewhere.
N/A
> Fix UI Overlap glitch in Export Project as PDF feature

- CHANGELOG.md
- layouts/shortcodes/iframe.html
*NOTE* There seems to still be some jumping, although to a much smaller degree.
Add a shortcode for iframes, to lazy load them
Add a shortcode for iframes, to lazy load them
https://spandigital.atlassian.net/browse/PRSDM-3870
http://localhost:8081/docs/span-handbook-draft/span-approach/05-project-artifacts/ has a lot of iframes, go there and see how they load and interact with the page. Compare the SPAN-Approach-2.0 handbook branch with the SPAN-Approach-2.0-test branch
N/A
> Add a shortcode for iframes, to lazy load them

- CHANGELOG.md
- layouts/partials/archive/table.html
- layouts/partials/common/archive.html
Refactors archive table content to a partial.
The SPAN Chronicles archive table required additional information about the section that the archived article belonged to for context. The current archive table is not extensible / customisable.
This moves archive table content to a partial `archive/table` that can be overriden for custom archive layouts.
[PRSDM-3804](https://spandigital.atlassian.net/browse/PRSDM-3804)
- Associated changes `span-chronicle-docs`: [PR](https://github.com/SPANDigital/span-chronicle-docs/pull/16)
> feat(archive): Moving article table to a a partial for extensibilty

- CHANGELOG.md
- layouts/partials/common/pages.html
Adds a configurable target minimum number of articles to be displayed per subsection in the menu, including archived articles if necessary.
SPAN Chronicles list pages should be able to configure a (targeted) minimum number of articles. This is to maintain some visibility of articles in sections which may not be updated with content regularly whose content may expire.
This adds logic to `common/pages` to update the archiving / displayed articles logic to allow showing archived articles if there aren't enough active articles in the section.
- _**NOTE**: This also fixes an issue that was discovered with diaply page caulations not taking into account section pages. Once archiving was set > 0days, all subfolders were not displayed, even if the articles they contained were not archived._
This …
> feat(pages): Adding a target minimum number of articles in sections

- CHANGELOG.md
- layouts/partials/article/root.html
- layouts/partials/common/pages.html
Fixes build error when permitted archive exposure param not set.
Logic in `common/pages` caused build errors when `archive.age` > 0 but `section.items` was not set.
Introduced in this [PR](https://github.com/SPANDigital/presidium-theme-website/pull/209).
This introduces a default when the parameter is missing to prevent the error.
- Also: renamed the number of archived articles permitted to be exposed from `Params.section.items` to `Params.archive.expose`
[PRSDM-3940](https://spandigital.atlassian.net/browse/PRSDM-3940)
> fix(pages): Fix build error when permitted archive exposure param not set

- CHANGELOG.md
- layouts/partials/searchmap/item.html
Adds frontmatter tags in to site searchmap
See [this PR](https://github.com/SPANDigital/presidium-services/pull/435) for context.
This adds frontmatter tags in to site searchmap.
[PRSDM-3938](https://spandigital.atlassian.net/browse/PRSDM-3938)
> feat(search): Add article tags to searchmap

- CHANGELOG.md
- assets/_sass/_structure.scss
Updated the anchor offset to 50px for all headings and article titles. This will prevent the title from being hidden behind the toolbar.
https://spandigital.atlassian.net/browse/PRSDM-4246
Import the site into enterprise and make sure the offset works
> Set heading anchor offset to 50px

- CHANGELOG.md
- layouts/partials/page/script.html
This PR fixes the following issue:
> When opening a drop-down in Presidium (seen in both the Handbook and Chronicle, the carrot reverses itself, so it points down when closed and points to the side when opened (see image).
https://spandigital.atlassian.net/browse/PRSDM-4185
Try and break it.
> Fix menu carrot state

- CHANGELOG.md
- layouts/partials/navigation/nav-item.html
- layouts/partials/navigation/root.html
This PR updates the nav to use the name defined in the config menu if there is no "_index.md" with a section name. 
https://spandigital.atlassian.net/browse/PRSDM-4330
> Use menu name if page name is undefined

- layouts/partials/article/root.html
- layouts/partials/page/header.html
- layouts/partials/page/list.html
Add feedback feature to _index articles.
Add feedback feature to _index articles.
Add WYSIWYG editing to __index articles.
Wraps the content in the same div wrapper with data as  articles in `layouts/partials/article/root.html`
Requires [presidium-js-enterprise](https://github.com/SPANDigital/presidium-js-enterprise/pull/374) to enable feedback and editing.
[PRSDM-3467](https://spandigital.atlassian.net/browse/PRSDM-3467)
Load your test site that has an _index : eg  presidium-docs-internal > apple > common-tasks
> Add feedback feature to _index articles

- layouts/partials/page/script.html
Recursively open the menu item of the selected page
[PRSDM-4416](https://spandigital.atlassian.net/browse/PRSDM-4416)
Try the menu navigation, it should open on selected sections
https://github.com/SPANDigital/presidium-theme-website/assets/34862470/88f82714-7f1d-4fd2-ba6d-83c0c201f79c
> PRSDM-4416 - Scroll-spy not expanding menu on Apple site

- CHANGELOG.md
- assets/_sass/_default-variables.scss
- assets/_sass/_structure.scss
- layouts/_default/baseof.html
- layouts/partials/page/script.html
This PR improves the page load performance and reduces layout shift by optimizing the order in which we load scripts and styles. 
Lighthouse score | Render timeline  
:-------------------------:|:-------------------------:
Lighthouse score | Render timeline  
:-------------------------:|:-------------------------:
https://spandigital.atlassian.net/browse/PRSDM-4555
> Improve page load by enabling preload and  reducing page shift

- CHANGELOG.md
- assets/_sass/_structure.scss
- assets/_sass/bootstrap/bootstrap/_scaffolding.scss
Removed the global font resets that are interfering with the enterprise styles.
See related PR https://github.com/SPANDigital/presidium-js-enterprise/pull/412
https://spandigital.atlassian.net/browse/PRSDM-4492
https://github.com/SPANDigital/presidium-theme-website/assets/48946187/fb2ae1d7-743f-4efd-a189-b2680862044e
> Remove global font styles

- CHANGELOG.md
- assets/_sass/bootstrap/bootstrap/_type.scss
Fix global h tags in the theme affecting enterprise
Fix global h tags in the theme affecting enterprise
https://spandigital.atlassian.net/browse/PRSDM-4638
Go to an article and open notifications. Notice the font.
Go to a dashboard page and open the notifications. Notice the font.
> Fix global h tags in theme affecting enterprise

- CHANGELOG.md
- layouts/index.compendium.json
- layouts/partials/compendium/item.html
- layouts/partials/compendium/root.html
This PR adds a new template to produce a searchmap in the format compendium requires it in.
[Issue](https://spandigital.atlassian.net/browse/PRSDM-4966)
```
{
"content": "\nTiVo partnered with SPAN to deliver a working demo for the TiVo sales team. The solution provided end users (car drivers) a data rich user experience and TiVo the ability to edit this data. Span iterated through the solution with TiVo and produced designs, a data model, an ingestion pipeline and the final working demo.\n\n{{\u003c iframe src=\"https://drive.google.com/file/d/1SMq1jHN6FxEQdQe64PkviOBDt5aCFpH-/preview\" \u003e}}\n",
"metadata": {
"compendium": {
"deep-link": "/docs/span-chronicle-docs/studies/#ti-vo-hybrid-radio-project",
"layer": 1,
"source-system": "Presidium"
},
"dublin-core": {
"creator": "Shayan", …
```
> PRSDM-4670: Add metadata onto artticle records

- CHANGELOG.md
- layouts/partials/searchmap/item.html
The builder expects tags to be strings, currently the Chronicle build is failing because certain tags are not. I updated the template to cast all tags to strings
https://spandigital.atlassian.net/browse/PRSDM-5056
> Stringify Tags

- CHANGELOG.md
- layouts/_default/baseof.html
- layouts/partials/page/script.html
Removed the config.js script from the theme, it's been replaced with a config provider, see [here](https://github.com/SPANDigital/presidium-js-enterprise/pull/557)
https://spandigital.atlassian.net/browse/PRSDM-5079
> Remove config js script

- CHANGELOG.md
- layouts/partials/common/filepath.html
- layouts/partials/common/uuid.html
- layouts/partials/page/header.html
- layouts/partials/page/list.html
Removed the deprecated `File.Path` and `File.UniqueId` that are causing the build to fail with the latest Hugo version, replaced it with a shortcodes.
https://spandigital.atlassian.net/browse/PRSDM-5150
> Fix deprecated file usage

- layouts/_default/baseof.html
I have updated the title page generated to allow for section - module in order to have less confusion when having multiple tabs open at different sections.
[Thread](https://a1391190.slack.com/archives/G01DUF77HMX/p1719154838989849?thread_ts=1719022645.390519&cid=G01DUF77HMX)
> Change index page title to allow less confusion between pages

- assets/_sass/_navbar.scss
Fixed the overlapping issue on the left nav for the article options display
[PRSDM-6014](https://spandigital.atlassian.net/browse/PRSDM-6014)
https://github.com/user-attachments/assets/7d3bb92b-ce14-42ba-9252-8a9e46c46651
> PRSDM-6014: Adjusted the article options display to address overlapping

- CHANGELOG.md
- layouts/partials/article/title.html
Ensure that lower level article titles are not larger than higher level articles
[PRSDM-5995](https://spandigital.atlassian.net/browse/PRSDM-5995)
Before:
After:
> PRSDM-5995: Ensure that lower level article titles are not larger than higher

- CHANGELOG.md
- assets/_sass/_image.scss
Set width to auto instead of 100% to fix images distortion
[PRSDM-6078](https://spandigital.atlassian.net/browse/PRSDM-6078)
Before:
After:
> fix: set width to auto to fix images distortion

- CHANGELOG.md
- assets/_sass/_navbar.scss
Align caret better with the link text in the left nav
[PRSDM-6128](https://spandigital.atlassian.net/browse/PRSDM-6128)
Normal:
Zoomed:
> fix: adjust line height for caret alignment

- CHANGELOG.md
- assets/_sass/_default-fonts.scss
Copy button of code block realigned to be in the code block instead of next to article title
Linked to: https://github.com/SPANDigital/presidium-js-enterprise/pull/681
[PRSDM-6124](https://spandigital.atlassian.net/browse/PRSDM-6124)
Build an enterprise site and find a codeblock
> fix: add relative pos for pre and code to fix copy button

- CHANGELOG.md
- assets/_sass/_navbar.scss
- layouts/partials/navigation/brand.html
- layouts/partials/page/script.html
Center navbar header content, fix navbar header image size & improve how navbar determines height
Center navbar header content, fix navbar header image size & improve how navbar determines height
https://spandigital.atlassian.net/browse/PRSDM-6146
Refer to video below
> fix: Center navbar header content, fix navbar header image size & improve how navbar determines height

- layouts/partials/article/root.html
- layouts/partials/page/header.html
https://spandigital.atlassian.net/browse/PRSDM-6121
> fix: PRSDM-6121 article divs need title field for voice over

- layouts/partials/article/root.html
fix: PRSDM-6121 articles need title field for accessibility purposes in the apple release
https://spandigital.atlassian.net/browse/PRSDM-6121
> fix: PRSDM-6121 articles need title field apple release

- layouts/shortcodes/index-toc.html
Shortcode to generate ToC of the pages for the current section or for the full site. 
Usage:
```
{{< index-toc >}}
or
{{< index-toc depth="2" >}}
or
{{< index-toc fullSite=true >}}
or
{{< index-toc fullSite=true depth="2" >}}
```
`fullSite` - when true show ToC for entire site(all sections in navbar), otherwise it will only generate a ToC for the current section
`depth` - How many subsections should be included in ToC
*Note:* Only works when used in an _index.html file
https://spandigital.atlassian.net/browse/PRSDM-6153
`{{< index-toc >}}`:
`{{< index-toc depth="2" >}}`:
`{{< index-toc fullSite=true >}}`:
`{{< index-toc fullSite=true depth="3">}}`:
> feat: toc for pages

- CHANGELOG.md
- layouts/partials/page/script.html
If a user has not set the width of the sidenav, the sidenav changes according to the size of the content. This fix sets the width of the sidenav if there isn't an existing width.
Below is a screen capture of the bug:
https://github.com/user-attachments/assets/7ea253d0-fd05-4900-a9f6-a521c8fe4a79
https://spandigital.atlassian.net/browse/PRSDM-6369
- In your local span-chronicle-docs repo, modify the theme import in config.yml to use the local version of presidium-theme-website
- Build SPAN Chronicle with presidium-content-builder
- Run presidium-js-enterprise
- Go to http://localhost:3000/docs/span-chronicle
- Open the Developer Tools and in the Application tab, select Storage > Local storage > http://localhost:3000
- If there is a sidenav key-value pair, delete it
- Reload the page and in …
> fix: set sidenav width if one does not exist PRSDM-6369

- layouts/partials/article/content.html
- layouts/partials/article/root.html
- layouts/partials/article/title.html
- layouts/partials/page/header.html
- layouts/partials/page/list.html
Removed arial-label from the div and added to <article> html element.
Removed arial-label from the div with `class="article"` and added it to <article> html element.
https://spandigital.atlassian.net/browse/PRSDM-6345
> feat: PRSDM-6345 aria labels on article html tags

- CHANGELOG.md
- assets/_sass/_structure.scss
- assets/_sass/_syntax.scss
- assets/_sass/bootstrap/bootstrap/_code.scss
Add horizontal scrollbar to code blocks
[PRSDM-5974](https://spandigital.atlassian.net/browse/PRSDM-5974)
* Use the branch `PRSDM-5974` on presidium-js-enterprise so the copy code button stays fixed (see https://github.com/SPANDigital/presidium-js-enterprise/pull/742)
* Pick a project and modify the theme import in `config.yml` to use the local version of presidium-theme-website
* Build the project
* Test
https://github.com/user-attachments/assets/78c3dae3-d549-4253-8efe-1fcabc0c9e4e
> refactor: Add horizontal scrollbar to code blocks

- layouts/_default/baseof.html
- Use enterprise script and style from content builder
- Have default fallback
- Function Length ([see reference](https://martinfowler.com/bliki/FunctionLength.html))
- Meaningful Names ([see reference](https://learning.oreilly.com/library/view/clean-code-a/9780136083238/chapter02.xhtml))
- DRY ([see reference](https://java-design-patterns.com/principles/#keep-things-dry))
- YAGNI ([see reference](https://java-design-patterns.com/principles/#yagni))
> refactor: version information for enterprise css and js

- CHANGELOG.md
- layouts/partials/article/title.html
Updates the article title template to dynamically assign heading levels based on the article's depth in the content hierarchy. The depth calculation logic has been adjusted to skip the global site title ($.Site.Title), which Hugo treats as an implicit top-level parent. By ignoring this site title, the change prevents an extra heading level from being added and ensures that each article’s header level correctly reflects its actual position within the hierarchy.
- [PRSDM-6186](https://spandigital.atlassian.net/browse/PRSDM-6186)
Before:
After:
- Function Length ([see reference](https://martinfowler.com/bliki/FunctionLength.html))
- Meaningful Names ([see reference](https://learning.oreilly.com/library/view/clean-code-a/9780136083238/chapter02.xhtml))
- DRY ([see …
> fix: Assign correct header to sub sections and articles
